### ISSUE TITLE
创建CaptureTab导致主界面崩溃

### ISSUE THREAD

**Issue by liuqun** [ithewei/hplayer#1]
如题, 我的Windows下没有USB摄像头. CaptureTab的initUI未处理这种情况, 结果主界面崩溃退出

临时解决方法是手动注释掉
https://github.com/ithewei/hplayer/blob/17fbe036c5b428f29f3a5a68b8e674e1e5a17ce0/src/ui/hopenmediadlg.cpp#L81

**Comment by ithewei** [comment]
谢谢你对该项目的关注和反馈，已经修复了下，我笔记本都有摄像头，所以没有发现问题，也测试不了，还请看下问题是否解决了
