### ISSUE TITLE
程序编译

### ISSUE THREAD

**Issue by kaichen1994** [ithewei/hplayer#3]
您好，请问您的程序可以编译成64位吗？

**Comment by liuqun** [comment]
我跟ithewei一直是用32位的Qt编译。个人认为64位并不会有任何性能提升，也就懒得捣鼓了。

**Comment by kaichen1994** [comment]
谢谢发自我的iPhone------------------ 原始邮件 ------------------发件人: 刘群  <notifications@github.com>发送时间: 2019年3月1日 16:23收件人: ithewei/hplayer <hplayer@noreply.github.com>抄送: kaichen1994 <kaichen94@163.com>, Author <author@noreply.github.com>主题: 回复：[ithewei/hplayer] 程序编译 (#3)我跟ithewei一直是用32位的Qt编译。个人认为64位并不会有任何性能提升，也就懒得捣鼓了。

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ithewei/hplayer","title":"ithewei/hplayer","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/ithewei/hplayer"}},"updates":{"snippets":[{"icon":"PERSON","message":"@liuqun in #3: 我跟ithewei一直是用32位的Qt编译。个人认为64位并不会有任何性能提升，也就懒得捣鼓了。"}],"action":{"name":"View Issue","url":"https://github.com/ithewei/hplayer/issues/3#issuecomment-468583705"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ithewei/hplayer/issues/3#issuecomment-468583705",
"url": "https://github.com/ithewei/hplayer/issues/3#issuecomment-468583705",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by hrdzkj** [comment]
编译异常：
1>src\qt\qtheaders.h(5): fatal error C1083: 无法打开包括文件: “hgl.h”: No such file or directory (编译源文件 tmp\moc\moc_mainwindow.cpp)

查找文件夹发现，不仅仅hgl.h没有，下面的.h文件也是没有的：
 "h.h"，
"hframe.h"，
 "hgui.h"，
