### ISSUE TITLE
Version of Qt and FFMPEG is used?

### ISSUE THREAD

**Issue by shujaatak** [ithewei/hplayer#7]
Can you please mention which version of Qt and FFMPEG is used to build this project?
I am on Windows having Qt5.13.2-msvc2017-64bit.

**Comment by ithewei** [comment]
see BUILD.md
In order to control the size of repo and focus on functionality rather than environment, only 
msvc14_x86 libs and dlls are provided.
Qt version is 5.11.1, and ffmpeg is 4.0.2,
If you want to compile with other version, for example, msvc2017-64bit, you can put libs into 3rd/lib/msvc15_x64, put dlls into bin/msvc15_x64, put headers into 3rd/include, then modify hplayer.pro
```
LIBS += -L$$PWD/3rd/lib/msvc14_x64
DESTDIR = $$PWD/bin/msvc14_x64
``` 
=> 
```
LIBS += -L$$PWD/3rd/lib/msvc15_x64
DESTDIR = $$PWD/bin/msvc15_x64
```

**Comment by shujaatak** [comment]
One thing I noticed is that if somehow link gets broken for a few minutes the rtsp stream does not reconnect automatically instead the program sometimes hangs and crashes due to disconnection. 
I wish the program could detect rtsp disconnection and then try to reconnect every once in a while instead of hanging and crashing.
By the way, hplayer user interface is so neat and beautiful...!

**Comment by shujaatak** [comment]
You can test rtsp stream using the following address:
rtsp://freja.hiof.no:1935/rtplive/definst/hessdalen03.stream
try to run the above rtsp stream and then turn off your wifi for a minute or two to simulate the broken link and then turn on wifi to see if the program automatically reconnect/play the video or not.

**Comment by shujaatak** [comment]
I noticed that the program can successfully play the rtsp stream if the disconnection time is few seconds but fails when disconnection time is about a minute or above.

**Comment by shujaatak** [comment]
Sorry I should have posted these comments in the other issue I have posted: [rtsp auto-reconnect issue](https://github.com/ithewei/hplayer/issues/6)
